2022-08-03 13:44:48: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:45:41: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:46:29: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:46:45: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:48:07: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:48:28: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:48:54: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 13:49:19: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 14:12:26: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 14:14:28: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 14:14:59: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
2022-08-03 14:17:15: ERROR - Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
Traceback (most recent call last):
  File "botfunction.py", line 32, in readConfig
Exception: config.ini file not found
